repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.3.7
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: trailing-whitespace
    - id: mixed-line-ending
exclude: "pyproject.toml"